title: Medieval Artists and Papers
markdown: kramdown
baseurl: "/MinDatabase"
permalink: /:path/:basename.html
exclude:
  - "prompts"
defaults:
  - scope:
      path: ""
    values:
      layout: default
